version: '3.1'

services:
  app:
    container_name: "gft-web-server"
    build:
      context: .
    networks:
      - gft-app-network

  db:
    container_name: "gft-postgres"
    image: postgres:12.4-alpine
    volumes:
      - "./postgres-data:/var/lib/postgresql/data:rw"
    restart: unless-stopped
    networks:
      - gft-app-network

  pg-admin:
    image: "dpage/pgadmin4:latest"
    container_name: "gft-pg-admin"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PORT: "${DB_PORT}"
    networks:
      - gft-app-network

  mailhog:
    image: "mailhog/mailhog:latest"
    container_name: "gft-mailhog"

  swagger-ui:
    image: "swaggerapi/swagger-ui:latest"
    container_name: "gft-swagger-ui"
    volumes:
      - "./:/home/data"
    networks:
      - gft-app-network

  redis:
    container_name: "gft-redis"
    image: redis:6.2.5-alpine
    volumes:
      - "./redis-data:/data:rw"
    networks:
      - gft-app-network

networks:
  gft-app-network:
    driver: "bridge"