ALTER TABLE user ADD COLUMN cityID INT NULL AFTER roleID;
ALTER TABLE user ADD CONSTRAINT FK_User_City FOREIGN KEY(cityID) REFERENCES city(id) ON UPDATE CASCADE ON DELETE SET NULL;
UPDATE user SET cityID = 1 WHERE id = 1;