ALTER TABLE restaurant ADD COLUMN guid VARCHAR(40) NOT NULL AFTER id;

CREATE TRIGGER TRG_BI_Restaurant
BEFORE INSERT ON restaurant
FOR EACH ROW
BEGIN
	SET NEW.guid = UUID();
END;

UPDATE restaurant SET guid = UUID();