ALTER TABLE user ADD guid VARCHAR(40) NOT NULL AFTER id;
DROP TRIGGER TRG_BI_User;

CREATE TRIGGER TRG_BI_User BEFORE INSERT ON user
FOR EACH ROW
BEGIN
	SET NEW.created_at = CURRENT_DATE;
	SET NEW.guid = UUID();
END;

UPDATE user SET guid = UUID();